[general]
import = ["./blood-moon.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "semibold" }
size = 15
